#pragma kernel Circles

RWTexture2D<float4> Input;
int count;
float4 circles[8];
float4 colors[4];

[numthreads(32, 32, 1)]
void Circles(uint3 id : SV_DispatchThreadID) {
    for (int i = 0; i < count; i++) {
        int xOffset = id.x - circles[i].x;
        int yOffset = id.y - circles[i].y;
        
        if (xOffset * xOffset + yOffset * yOffset < circles[i].z) {
            Input[id.xy] = colors[circles[i].w];
        }
    }
}