#pragma kernel Stroke

RWTexture2D<float4> Input;
float4 color;

[numthreads(32, 32, 1)]
void Stroke(uint3 id : SV_DispatchThreadID) {
    if (Input[id.xy].w == 0) {
        if (Input[uint2 (id.x - 1, id.y)].w == 1 ||
            Input[uint2 (id.x + 1, id.y)].w == 1 ||
            Input[uint2 (id.x, id.y - 1)].w == 1 ||
            Input[uint2 (id.x, id.y + 1)].w == 1) {

            Input[id.xy] = color;
        }
    }
}