#pragma kernel Stroke

RWTexture2D<float4> Input;
RWStructuredBuffer<float4> Pallete;
int color;

[numthreads(8, 8, 1)]
void Stroke(uint3 id : SV_DispatchThreadID) {
    if (Input[id.xy].w == 0) {
        if (Input[uint2 (id.x - 1, id.y)].w == 1 ||
            Input[uint2 (id.x + 1, id.y)].w == 1 ||
            Input[uint2 (id.x, id.y - 1)].w == 1 ||
            Input[uint2 (id.x, id.y + 1)].w == 1) {

            Input[id.xy] = Pallete[color];
        }
    }
}